### PR TITLE
Sponsor UI 🖌️

### LINKED ISSUE #65: Sponsors Screen -> UI and Linking
### Is your feature request related to a problem? Please describe.

Creating the UI of the screen and then linking the completed screen to the correct position in the widget tree of the app.

### PR DESCRIPTION
**Pull request by TreavVasu**
### Description

**Type of Change:** (Delete irrelevant options)
- Code
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [x] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Mention the dependencies/packages/plugins that have been added (if any)**
- rxdart

### CODE REVIEW

**Comment by TreavVasu** [comment]
Screenshot_1615125062
Screenshot_1615125068

**Review by werainkhatri — APPROVED** [review]
LGTM
Merge the PR (TreavVasu#6) and I'll merge it.

**Comment by werainkhatri** [comment]
Another major bugfix. Please take care of such changes and test everything!
TreavVasu#10

**Comment by TreavVasu** [comment]
Changes will be made tomorrow as suggested.

**Comment by werainkhatri** [comment]
TreavVasu#11 last fix and it's done.

**Pull request merged**
